In [ ]:
import numpy as np

In [40]:
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:

m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [36]:
array = np.random.randint(1, 11, size=(5, 5))
print(array)


[[ 2  4 10  7 10]
 [ 6  3  5  5  7]
 [ 7  6  8  5  1]
 [ 5  2  5  1  8]
 [10  1  9  3  6]]


In [42]:
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Перший масив:")
print(array1)
print("Другий масив:")
print(array2)
print("Результат додавання:")
print(addition)
print("Результат віднімання:")
print(subtraction)
print("Результат множення:")
print(multiplication)


Перший масив:
[ 2  6  2 10  1]
Другий масив:
[3 2 8 8 5]
Результат додавання:
[ 5  8 10 18  6]
Результат віднімання:
[-1  4 -6  2 -4]
Результат множення:
[ 6 12 16 80  5]


In [44]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([7, 6, 5, 4, 3, 2, 1])
print(a * b)
print(np.dot(a, b))

[ 7 12 15 16 15 12  7]
84


In [52]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2,3))
c = np.dot(a, b)
print("Матриця а")
print(a)
print("Матриця b")
print(b)
print("Множення матриць")
print(c)

Матриця а
[[ 5  4]
 [10  9]]
Матриця b
[[6 5 8]
 [2 5 7]]
Множення матриць
[[ 38  45  68]
 [ 78  95 143]]


In [57]:
a = np.random.randint(1, 11, size=(2, 2))
a_inv = np.linalg.inv(a)
print("Матриця а")
print(a)
print("Обернена")
print(a_inv)

Матриця а
[[3 8]
 [8 9]]
Обернена
[[-0.24324324  0.21621622]
 [ 0.21621622 -0.08108108]]


In [61]:
a = np.random.rand(4,4)
transposed_matrix = np.transpose(a)
print("Матриця")
print(a)

print("\nТранспонована матриця:")
print(transposed_matrix)

Матриця
[[0.76540507 0.28581946 0.35587764 0.38684237]
 [0.63990384 0.37612283 0.73360103 0.14714327]
 [0.69907309 0.8760561  0.28040416 0.32080801]
 [0.42227774 0.01754889 0.0103942  0.0771196 ]]

Транспонована матриця:
[[0.76540507 0.63990384 0.69907309 0.42227774]
 [0.28581946 0.37612283 0.8760561  0.01754889]
 [0.35587764 0.73360103 0.28040416 0.0103942 ]
 [0.38684237 0.14714327 0.32080801 0.0771196 ]]


In [62]:
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)
result = np.dot(a, b)

print("Матриця")
print(a)

print("\nВектор")
print(b)

print("\nРезультат множення матриці на вектор:")
print(result)

Матриця
[[6 7 8 9]
 [2 1 9 7]
 [3 9 8 1]]

Вектор
[ 2 10  6  6]

Результат множення матриці на вектор:
[184 110 150]


In [64]:
a = np.random.rand(2, 3)
b = np.random.rand(3)
result = np.dot(a, b)

print("Матриця")
print(a)

print("\nВектор")
print(b)

print("\nРезультат множення матриці на вектор:")
print(result)

Матриця
[[0.38619586 0.17749925 0.09916723]
 [0.89488242 0.913447   0.21318614]]

Вектор
[0.65935878 0.05753246 0.79005612]

Результат множення матриці на вектор:
[0.34320128 0.81103044]


In [65]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
c = a*b

print("Перша матриця")
print(a)

print("\nДруга матриця")
print(b)

print("\nРезультат поелементного множення матриць:")
print(c)

Перша матриця
[[9 5]
 [2 1]]

Друга матриця
[[ 6 10]
 [ 7  5]]

Результат поелементного множення матриць:
[[54 50]
 [14  5]]


In [66]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
c = np.dot(a, b)

print("Перша матриця")
print(a)

print("\nДруга матриця")
print(b)

print("\nДобуток матриць:")
print(c)

Перша матриця
[[ 7  7]
 [ 7 10]]

Друга матриця
[[9 6]
 [2 9]]

Добуток матриць:
[[ 77 105]
 [ 83 132]]


In [68]:
a = np.random.randint(1, 101, size=(5, 5))
sum = np.sum(a)

print("Матриця")
print(a)

print("\nСума елементів матриці:")
print(sum)

Матриця
[[86 38 98 53 32]
 [47 15 47 97 27]
 [68 24 64 43 75]
 [66 57 23  7 19]
 [33 80 82 39 93]]

Сума елементів матриці:
1313


In [69]:
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
c = a - b

print("Перша матриця:")
print(a)

print("\nДруга матриця")
print(b)

print("\nРізниця матриць")
print(c)


Перша матриця:
[[10 10  8  8]
 [ 4  4 10  9]
 [10  3 10  6]
 [ 1  1  5  9]]

Друга матриця
[[8 1 2 8]
 [9 7 7 8]
 [5 7 5 4]
 [3 5 3 6]]

Різниця матриць
[[ 2  9  6  0]
 [-5 -3  3  1]
 [ 5 -4  5  2]
 [-2 -4  2  3]]


In [70]:
a = np.random.rand(3, 3)
row_sums = np.sum(a, axis=1).reshape(-1, 1)


print("Матриця")
print(a)

print("\nВектор-стовпчик з сумами елементів кожного рядка:")
print(row_sums)


Матриця
[[0.05798189 0.6315764  0.8993918 ]
 [0.18646027 0.79035507 0.87050568]
 [0.17909269 0.02758464 0.36442844]]

Вектор-стовпчик з сумами елементів кожного рядка:
[[1.58895009]
 [1.84732102]
 [0.57110577]]


In [73]:
a = np.random.randint(1, 11, size=(3, 4))
squared_matrix = np.square(a)

print("матриця:")
print(a)

print("\nМатриця з квадратами чисел:")
print(squared_matrix)


матриця:
[[ 5  4 10  3]
 [ 5  6  4 10]
 [ 1  7  6 10]]

Матриця з квадратами чисел:
[[ 25  16 100   9]
 [ 25  36  16 100]
 [  1  49  36 100]]


In [74]:
a = np.random.randint(1, 51, size=4)
sqrt_vector = np.sqrt(a)

print("вектор:")
print(vector)

print("\nВектор з квадратними коренями:")
print(sqrt_vector)


вектор:
[ 1  2  3  4  5  6  7  8  9 10]

Вектор з квадратними коренями:
[2.44948974 6.08276253 6.32455532 4.47213595]
